### PR TITLE
Flake8 black mypy support

### PR DESCRIPTION
**Pull request by nth10sd**
Type information is being added, also useful for FuzzManager. Also making tweaks for flake8 and black formatting happiness (`flake8-4.0.1`, `black 21.12b0` with `mypy-0.931`) for my sanity.

~~I'll be using type syntax from `__future__`, feel free to convert it back. (Automatically using a tool?)~~

CI is [on a branch in my fork](https://github.com/nth10sd/orion/actions?query=branch%3Aflake8-black-mypy-support).

### CODE REVIEW

**Comment by nth10sd** [comment]
@jschwartzentruber I've taken this as far as I can for now while minimizing adding ignores or `Any`s. (721/846 issues fixed, or 85.22%)

Please feel free to take this to completion.

**Comment by nth10sd** [comment]
@jschwartzentruber I ported to old style type information without needing to import from `__future__` and added a bunch more `Any`s wrt. `*args`, `**kwargs` and for `Dict`s. That's almost 90% type information provided.

Serious question in case this bitrots further. Would you consider using `Any`s for the remaining type information and land this first (after merging in master changes)? There's been quite a lot of development on the master branch that makes it hard to keep maintaining this PR. Also attention @pyoor since he's had some commits.

**Comment by jschwartzentruber** [comment]
Finished and merged in #168 . Thanks @nth10sd !

**Comment by sylvestre** [comment]
impressive work bravo :)

**Pull request closed without merging**
